modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''
Всплывающие очки за убийства в стиле старых Call of Duty для мода TacZ:
First Blood, Headshot, Longshot, No-Scope, Quickscope, 360 No-Scope, Multi Kill и другие.
'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "tacz"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
